# Generated by Django 4.0.3 on 2022-04-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.IntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('startDate', models.DateField()),
                ('Duration', models.IntegerField()),
                ('StopAnswering', models.IntegerField()),
                ('StopScoreboard', models.IntegerField()),
                ('Penalty', models.IntegerField()),
                ('MaxFileSize', models.IntegerField()),
                ('URL', models.CharField(default='Link', max_length=200)),
                ('ContestM', models.IntegerField()),
                ('ContestL', models.IntegerField()),
            ],
        ),
    ]
