# Generated by Django 4.0.3 on 2022-04-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='ContestL',
            new_name='Contest_Main_site_number',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='ContestM',
            new_name='Contest_local_site_numer',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='URL',
            new_name='Contest_mainsite_URL',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='MaxFileSize',
            new_name='Max_file_size_allowed_for_teams',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='Numero',
            new_name='Number',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='StopAnswering',
            new_name='Stop_Answering',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='StopScoreboard',
            new_name='Stop_Scoreboard',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='startDate',
            new_name='start_Date',
        ),
    ]
