# Generated by Django 4.0.3 on 2022-04-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_alter_contest_contest_mainsite_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='Contest_mainsite_URL',
            field=models.CharField(default='Link', max_length=200),
        ),
    ]
