# Generated by Django 4.0.3 on 2022-04-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_alter_contest_contest_mainsite_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('User_Full_Name', models.CharField(max_length=200)),
                ('User_Description', models.CharField(max_length=500)),
                ('Old_Password', models.CharField(max_length=200)),
                ('New_Password', models.CharField(max_length=200)),
                ('Retype_New_Password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='contest',
            name='Contest_mainsite_URL',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contest',
            name='Duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='Max_file_size_allowed_for_teams',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='Penalty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='Stop_Answering',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='Stop_Scoreboard',
            field=models.IntegerField(),
        ),
    ]
